Repository maddielaw/rancid-tomatillos, pull requests merged in 2022-03, with the labels that each got.

#7 Display all movies/zl
  src/App.css
  src/App.js
  src/apiCalls.js
  src/components/App.js
  src/components/MovieDetail.js
  src/components/MovieOverview.js
  src/components/MoviesContainer.js
  src/index.css
  src/index.js
  src/logo.svg
  src/movieData.js
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/MovieDetail.css
  src/styles/MovieOverview.css
  src/styles/MoviesContainer.css
Labels: new feature

#9 Feature/display single movie/ml
  src/App.css
  src/components/App.js
  src/components/MovieDetail.js
  src/components/MovieOverview.js
  src/components/MoviesContainer.js
  src/styles/MovieDetail.css
  src/styles/MoviesContainer.css
Labels: new feature, styling

#14 Api calls/zl
  public/index.html
  src/apiCalls.js
  src/components/App.js
  src/components/MovieDetail.js
  src/components/MovieOverview.js
  src/movieData.js
  src/styles/MovieDetail.css
  src/styles/MovieOverview.css
Labels: bug / refactor, new feature

#16 Formatting/zl
  package-lock.json
  package.json
  src/components/MovieDetail.js
  src/styles/MovieDetail.css
Labels: bug / refactor, styling

#20 Feature/react router/ml
  package-lock.json
  package.json
  src/App.css
  src/components/App.js
  src/components/MovieDetail.js
  src/components/MovieOverview.js
  src/index.js
Labels: bug / refactor, new feature

#25 Iteration four cypress
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/movie_display_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/components/App.js
  src/components/Error.js
  src/components/MovieDetail.js
  src/components/MovieOverview.js
  src/styles/Error.css
  src/styles/MovieDetail.css
Labels: bug / refactor, new feature
